### ISSUE TITLE
Is the Slack page dead ?

### ISSUE THREAD

**Issue by SheatNoisette** [nlp-compromise/fr-compromise#6]
The README says there is a slack page for the project, but it leads to a 404 error page. Is the Slack link dead for the fr variant of the project ?

**Comment by spencermountain** [comment]
hey @SheatNoisette we've just resumed work on fr-compromise, and could really use some help, if you're interested.
Yeah, we tried moving chat to spectrum, so it would be googleable - it's pretty quiet in there, but here's the link - https://spectrum.chat/nlp-compromise
